/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author hassa
 */
public class AssignSupervisorGUI extends javax.swing.JFrame {

    /**
     * Creates new form AssignSupervisorGUI
     */
    public AssignSupervisorGUI() {
        initComponents();
        // Populate project and supervisor lists
        populateProjectList();
        populateSupervisorList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        supervisorList = new javax.swing.JList<>();
        assignButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel3.setText("Assign Supervisor");

        projectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(projectList);

        supervisorList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(supervisorList);

        assignButton.setText("Assign");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(assignButton)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assignButton)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        String selectedProject = projectList.getSelectedValue();
        String selectedSupervisor = supervisorList.getSelectedValue();
        if (selectedProject != null && selectedSupervisor != null) {
            // Parse selected project and supervisor to extract relevant information
            String[] projectParts = selectedProject.split(" - ");
            String[] supervisorParts = selectedSupervisor.split(" - ");

            String projectId = projectParts[0];
            String supervisorId = supervisorParts[0];

            // Perform assignment operation
            // Example: write code to save the assignment to a database or file
            JOptionPane.showMessageDialog(this, "Assigned project " + projectId + " to supervisor " + supervisorId);
        } else {
            JOptionPane.showMessageDialog(this, "Please select both a project and a supervisor.");
        }
    }

    // Main method for testing
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignSupervisorGUI().setVisible(true);
            }
        });
    }//GEN-LAST:event_assignButtonActionPerformed

    private void populateProjectList() {
        DefaultListModel<String> projectModel = new DefaultListModel<>();
        try (BufferedReader br = new BufferedReader(new FileReader("project.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Assuming each line contains project details separated by ","
                String[] parts = line.split(",");
                if (parts.length >= 2) {
                    projectModel.addElement(parts[0] + " - " + parts[1]); // Display both project id and name
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        projectList.setModel(projectModel);
    }
    
    private void populateSupervisorList() {
        DefaultListModel<String> supervisorModel = new DefaultListModel<>();
        try (BufferedReader br = new BufferedReader(new FileReader("lecturer.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Assuming each line contains lecturer details separated by newline
                String[] parts = line.split("\n");
                for (String part : parts) {
                    // Extract staff ID and name from each part
                    if (part.startsWith("Name:")) {
                        String name = part.substring(6).trim(); // Extract name
                        line = br.readLine(); // Read next line
                        if (line != null && line.startsWith("Staff ID:")) {
                            String staffId = line.substring(10).trim(); // Extract staff ID
                            supervisorModel.addElement(staffId + " - " + name); // Display both staff ID and name
                        }
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        supervisorList.setModel(supervisorModel);
    }
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> projectList;
    private javax.swing.JList<String> supervisorList;
    // End of variables declaration//GEN-END:variables
}
