/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author dongk
 */
public class EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    public EditStudent() {
        initComponents();
        EditAndDeleteOption editAndDeleteOption = new EditAndDeleteOption();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        TpNumTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        contactNumTxt = new javax.swing.JTextField();
        programmeTxt = new javax.swing.JTextField();
        ShowButtonActionPerformed = new javax.swing.JButton();
        EditButtonActionPerformed = new javax.swing.JButton();
        DeleteButtonActionPerformed = new javax.swing.JButton();
        SaveButtonActionPerformed = new javax.swing.JButton();
        ReturnButtonActionPerformed = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentProfileData = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Student Edit");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Enter Name:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("Enter TP Num: ");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setText("Enter Email:");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setText("Enter ContactNum:");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel6.setText("Enter Programme:");

        ShowButtonActionPerformed.setBackground(java.awt.Color.gray);
        ShowButtonActionPerformed.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        ShowButtonActionPerformed.setText("Show");
        ShowButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformedActionPerformed(evt);
            }
        });

        EditButtonActionPerformed.setBackground(java.awt.Color.gray);
        EditButtonActionPerformed.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        EditButtonActionPerformed.setText("Edit");
        EditButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformedActionPerformed(evt);
            }
        });

        DeleteButtonActionPerformed.setBackground(java.awt.Color.gray);
        DeleteButtonActionPerformed.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        DeleteButtonActionPerformed.setText("Delete");
        DeleteButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformedActionPerformed(evt);
            }
        });

        SaveButtonActionPerformed.setBackground(java.awt.Color.gray);
        SaveButtonActionPerformed.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        SaveButtonActionPerformed.setText("Save");
        SaveButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformedActionPerformed(evt);
            }
        });

        ReturnButtonActionPerformed.setBackground(java.awt.Color.gray);
        ReturnButtonActionPerformed.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        ReturnButtonActionPerformed.setText("Return");
        ReturnButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformedActionPerformed(evt);
            }
        });

        StudentProfileData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "TP Number", "Email", "ContactNum", "Programme"
            }
        ));
        StudentProfileData.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jScrollPane1.setViewportView(StudentProfileData);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/output-onlinepngtools.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(programmeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactNumTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TpNumTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(167, 167, 167)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ShowButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditButtonActionPerformed)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteButtonActionPerformed)
                        .addGap(18, 18, 18)
                        .addComponent(SaveButtonActionPerformed)
                        .addGap(18, 18, 18)
                        .addComponent(ReturnButtonActionPerformed)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DeleteButtonActionPerformed, EditButtonActionPerformed, ReturnButtonActionPerformed, SaveButtonActionPerformed, ShowButtonActionPerformed});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TpNumTxt, contactNumTxt, emailTxt, nameTxt, programmeTxt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TpNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(programmeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButtonActionPerformed)
                    .addComponent(DeleteButtonActionPerformed)
                    .addComponent(SaveButtonActionPerformed)
                    .addComponent(ReturnButtonActionPerformed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DeleteButtonActionPerformed, EditButtonActionPerformed, ReturnButtonActionPerformed, SaveButtonActionPerformed, ShowButtonActionPerformed});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TpNumTxt, contactNumTxt, emailTxt, nameTxt, programmeTxt});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) StudentProfileData.getModel();
        int selectedRowIndex = StudentProfileData.getSelectedRow();
        model.setValueAt(nameTxt.getText(), selectedRowIndex, 0);
        model.setValueAt(TpNumTxt.getText(), selectedRowIndex, 1);
        model.setValueAt(emailTxt.getText(), selectedRowIndex, 2);
        model.setValueAt(contactNumTxt.getText(), selectedRowIndex, 3);
        model.setValueAt(programmeTxt.getText(), selectedRowIndex, 4);
    }//GEN-LAST:event_EditButtonActionPerformedActionPerformed

    private void ShowButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) StudentProfileData.getModel();
        // Always set the count of row as 0 when pressed the Show Button
        model.setRowCount(0);
        
        try(BufferedReader reader = new BufferedReader(new FileReader("student.txt"))){
            String line;
            String[] studentData = new String[5];
            while ((line = reader.readLine())!= null){
                if(line.startsWith("Name: ")){
                    studentData[0] = line.substring(6);
                }else if(line.startsWith("TP Number: ")){
                    studentData[1] = line.substring(11);
                }else if(line.startsWith("Email Address: ")){
                    studentData[2] = line.substring(15);
                }else if(line.startsWith("Contact Number: ")){
                    studentData[3] = line.substring(16);
                }else if(line.startsWith("Programme Name: ")){
                    studentData[4] = line.substring(16);
                    model.addRow(studentData);
                    studentData = new String[5];
            }
        }
        JOptionPane.showMessageDialog(null,"Student Profile loaded successfully !");    
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error loading the Student Profile !");
        }
    }//GEN-LAST:event_ShowButtonActionPerformedActionPerformed

    private void ReturnButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        EditAndDeleteOption editAndDeleteOption = new EditAndDeleteOption();
        editAndDeleteOption.show();
        dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformedActionPerformed

    private void DeleteButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) StudentProfileData.getModel();
        int selectedRowIndex = StudentProfileData.getSelectedRow();
        
        if(selectedRowIndex == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to change !");
            return;
        }
        
        String name = (String) model.getValueAt(selectedRowIndex, 0);
        model.removeRow(selectedRowIndex);
        
        File inputFile = new File("student.txt");
        File tempFile = new File("tempstudent.txt");
        
        try(BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))){
            
            String line;
            boolean found = false;
            
            while ((line = reader.readLine()) != null) {
            if (line.startsWith("Name: ") && line.substring(6).equals(name)) {
                // Skip the next 5 lines in the original file (the old details)
                for (int i = 0; i < 5; i++) {
                    reader.readLine();
                }
                found = true;
            } else {
                writer.write(line + "\n");
            }
        }
         if (!found) {
            JOptionPane.showMessageDialog(null, "Cannot find the related student name!");
        }    

      } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(null, "File not found: " + e.getMessage());
      } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error reading or writing file: " + e.getMessage());
      }

      if (inputFile.delete()) {
        if (!tempFile.renameTo(inputFile)) {
            JOptionPane.showMessageDialog(null, "Cannot rename the temporary file!");
        } else {
            JOptionPane.showMessageDialog(null, "Student details deleted successfully!");
        }
      } else {
        JOptionPane.showMessageDialog(null, "Cannot delete original file!");
      }
    }//GEN-LAST:event_DeleteButtonActionPerformedActionPerformed

    private void SaveButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) StudentProfileData.getModel();
        int selectedRowIndex = StudentProfileData.getSelectedRow();
        
        if(selectedRowIndex == -1){
            JOptionPane.showMessageDialog(null, "Please select a row to change !");
            return;
        }
        
        String name = (String)model.getValueAt(selectedRowIndex, 0);
        String TpNum = (String)model.getValueAt(selectedRowIndex, 1);
        String email = (String)model.getValueAt(selectedRowIndex, 2);
        String contactNum = (String)model.getValueAt(selectedRowIndex, 3);
        String programme = (String)model.getValueAt(selectedRowIndex, 4);
        
        try{
            File inputFile = new File("student.txt");
            File tempFile = new File("tempstudent.txt");
            
            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));
            
            String line;
            boolean found = false;
      
            while ((line = reader.readLine()) != null) {
            if (line.startsWith("Name: ") && line.substring(6).equals(name)) {
                writer.write("Name: " + name + "\n");
                writer.write("Staff ID: " + TpNum + "\n");
                writer.write("Email Address: " + email + "\n");
                writer.write("Contact Number: " + contactNum + "\n");
                writer.write("Job Title: " + programme + "\n");
                writer.write("\n");
                // Skip the next 5 lines in the original file (the old details)
                for (int i = 0; i < 5; i++) {
                    reader.readLine();
                }
                found = true;

            }else{
              writer.write(line + "\n");
            }
        }
            
        writer.close();
        reader.close();
        
        if (found) {
            if (!inputFile.delete()) {
                JOptionPane.showMessageDialog(null, "Could not delete original file");
                return;
            }
            if (!tempFile.renameTo(inputFile)) {
                JOptionPane.showMessageDialog(null, "Could not rename temporary file");
            } else {
                JOptionPane.showMessageDialog(null, "Student details updated successfully!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cannot find the related student name!");
            tempFile.delete(); // cleanup the temp file if no matching lecturer found
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error replacing the student profile: " + e.getMessage());
     }
    }//GEN-LAST:event_SaveButtonActionPerformedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButtonActionPerformed;
    private javax.swing.JButton EditButtonActionPerformed;
    private javax.swing.JButton ReturnButtonActionPerformed;
    private javax.swing.JButton SaveButtonActionPerformed;
    private javax.swing.JButton ShowButtonActionPerformed;
    private javax.swing.JTable StudentProfileData;
    private javax.swing.JTextField TpNumTxt;
    private javax.swing.JTextField contactNumTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField programmeTxt;
    // End of variables declaration//GEN-END:variables
}
