/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author hassa
 */
public class ViewStatusGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewStatusGUI
     */
    public ViewStatusGUI() {
        initComponents();
        // Populate project list
        populateProjectList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusTextArea = new javax.swing.JTextArea();
        studentRadioButton = new javax.swing.JRadioButton();
        intakeRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        titleLabel.setText("View Project Status");

        projectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(projectList);

        statusTextArea.setColumns(20);
        statusTextArea.setRows(5);
        jScrollPane2.setViewportView(statusTextArea);

        studentRadioButton.setText("Student");

        intakeRadioButton.setText("Intake");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentRadioButton)
                    .addComponent(intakeRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(studentRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intakeRadioButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateProjectList() {
        DefaultListModel<String> projectModel = new DefaultListModel<>();
        try (BufferedReader br = new BufferedReader(new FileReader("project.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Assuming each line contains project details separated by ","
                String[] parts = line.split(",");
                if (parts.length >= 2) {
                    projectModel.addElement(parts[0] + " - " + parts[1]); // Display both project id and name
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        projectList.setModel(projectModel);
    }
    
    private void loadStatus(String selectedProject, String selectedOption) {
        // Load status for the selected project and option (student or intake)
        // This is just a placeholder method
        // You can replace this with your logic to fetch status from a database or file
        String status = "Status for project: " + selectedProject + " (By " + selectedOption + ")\n";
        status += "-------------------------------------\n";
        if (selectedOption.equals("student")) {
            status += "Assigned Students:\n";
            status += "Student 1\n";
            status += "Student 2\n";
        } else {
            status += "Assigned Intake:\n";
            status += "Intake A\n";
            status += "Intake B\n";
        }
        status += "-------------------------------------\n";
        status += "Supervisor: John Doe\n";
        statusTextArea.setText(status);
    }

    // Main method for testing
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStatusGUI().setVisible(true);
            }
        });
    }
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton intakeRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> projectList;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JTextArea statusTextArea;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
